-- MySQL Script generated by MySQL Workbench
-- Tue Apr 25 19:01:10 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema jugos_ventas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jugos_ventas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jugos_ventas` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
-- -----------------------------------------------------
-- Schema ventas_jugos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ventas_jugos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ventas_jugos` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `jugos_ventas` ;

-- -----------------------------------------------------
-- Table `jugos_ventas`.`tabla_de_vendedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jugos_ventas`.`tabla_de_vendedores` (
  `MATRICULA` VARCHAR(5) NOT NULL,
  `NOMBRE` VARCHAR(100) NULL DEFAULT NULL,
  `PORCENTAJE_COMISION` FLOAT NULL DEFAULT NULL,
  `FECHA_ADMISION` DATE NULL DEFAULT NULL,
  `VACACIONES` BIT(1) NULL DEFAULT NULL,
  `BARRIO` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`MATRICULA`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `jugos_ventas`.`tabla_de_clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jugos_ventas`.`tabla_de_clientes` (
  `DNI` VARCHAR(11) NOT NULL,
  `NOMBRE` VARCHAR(100) NULL DEFAULT NULL,
  `DIRECCION_1` VARCHAR(150) NULL DEFAULT NULL,
  `DIRECCION_2` VARCHAR(150) NULL DEFAULT NULL,
  `BARRIO` VARCHAR(50) NULL DEFAULT NULL,
  `CIUDAD` VARCHAR(50) NULL DEFAULT NULL,
  `ESTADO` VARCHAR(2) NULL DEFAULT NULL,
  `CP` VARCHAR(8) NULL DEFAULT NULL,
  `FECHA_DE_NACIMIENTO` DATE NULL DEFAULT NULL,
  `EDAD` SMALLINT NULL DEFAULT NULL,
  `SEXO` VARCHAR(1) NULL DEFAULT NULL,
  `LIMITE_DE_CREDITO` FLOAT NULL DEFAULT NULL,
  `VOLUMEN_DE_COMPRA` FLOAT NULL DEFAULT NULL,
  `PRIMERA_COMPRA` BIT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`DNI`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `jugos_ventas`.`facturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jugos_ventas`.`facturas` (
  `DNI` VARCHAR(11) NOT NULL,
  `MATRICULA` VARCHAR(5) NOT NULL,
  `FECHA_VENTA` DATE NULL DEFAULT NULL,
  `NUMERO` INT NOT NULL,
  `IMPUESTO` FLOAT NOT NULL,
  PRIMARY KEY (`NUMERO`),
  INDEX `MATRICULA` (`MATRICULA` ASC) VISIBLE,
  INDEX `CPF` (`DNI` ASC) VISIBLE,
  CONSTRAINT `facturas_ibfk_1`
    FOREIGN KEY (`MATRICULA`)
    REFERENCES `jugos_ventas`.`tabla_de_vendedores` (`MATRICULA`),
  CONSTRAINT `facturas_ibfk_2`
    FOREIGN KEY (`DNI`)
    REFERENCES `jugos_ventas`.`tabla_de_clientes` (`DNI`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `jugos_ventas`.`tabla_de_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jugos_ventas`.`tabla_de_productos` (
  `CODIGO_DEL_PRODUCTO` VARCHAR(10) NOT NULL,
  `NOMBRE_DEL_PRODUCTO` VARCHAR(50) NULL DEFAULT NULL,
  `TAMANO` VARCHAR(10) NULL DEFAULT NULL,
  `SABOR` VARCHAR(20) NULL DEFAULT NULL,
  `ENVASE` VARCHAR(20) NULL DEFAULT NULL,
  `PRECIO_DE_LISTA` FLOAT NOT NULL,
  PRIMARY KEY (`CODIGO_DEL_PRODUCTO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `jugos_ventas`.`items_facturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jugos_ventas`.`items_facturas` (
  `NUMERO` INT NOT NULL,
  `CODIGO_DEL_PRODUCTO` VARCHAR(10) NOT NULL,
  `CANTIDAD` INT NOT NULL,
  `PRECIO` FLOAT NOT NULL,
  PRIMARY KEY (`NUMERO`, `CODIGO_DEL_PRODUCTO`),
  INDEX `CODIGO_DEL_PRODUCTO` (`CODIGO_DEL_PRODUCTO` ASC) VISIBLE,
  CONSTRAINT `items_facturas_ibfk_1`
    FOREIGN KEY (`CODIGO_DEL_PRODUCTO`)
    REFERENCES `jugos_ventas`.`tabla_de_productos` (`CODIGO_DEL_PRODUCTO`),
  CONSTRAINT `items_facturas_ibfk_2`
    FOREIGN KEY (`NUMERO`)
    REFERENCES `jugos_ventas`.`facturas` (`NUMERO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `ventas_jugos` ;

-- -----------------------------------------------------
-- Table `ventas_jugos`.`tb_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_jugos`.`tb_cliente` (
  `DNI` VARCHAR(11) NOT NULL,
  `NOMBRE` VARCHAR(100) NULL DEFAULT NULL,
  `DIRECCION` VARCHAR(150) NULL DEFAULT NULL,
  `BARRIO` VARCHAR(50) NULL DEFAULT NULL,
  `CIUDAD` VARCHAR(50) NULL DEFAULT NULL,
  `ESTADO` VARCHAR(10) NULL DEFAULT NULL,
  `CP` VARCHAR(10) NULL DEFAULT NULL,
  `FECHA_NACIMIENTO` DATE NULL DEFAULT NULL,
  `EDAD` SMALLINT NULL DEFAULT NULL,
  `SEXO` VARCHAR(1) NULL DEFAULT NULL,
  `LIMITE_CREDITO` FLOAT NULL DEFAULT NULL,
  `VOLUMEN_COMPRA` FLOAT NULL DEFAULT NULL,
  `PRIMERA_COMPRA` BIT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`DNI`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ventas_jugos`.`tb_vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_jugos`.`tb_vendedor` (
  `MATRICULA` VARCHAR(5) NOT NULL,
  `NOMBRE` VARCHAR(100) NULL DEFAULT NULL,
  `BARRIO` VARCHAR(50) NULL DEFAULT NULL,
  `COMISION` FLOAT NULL DEFAULT NULL,
  `FECHA_ADMISION` DATE NULL DEFAULT NULL,
  `DE_VACACIONES` BIT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`MATRICULA`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ventas_jugos`.`tb_factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_jugos`.`tb_factura` (
  `NUMERO` VARCHAR(5) NOT NULL,
  `FECHA` DATE NULL DEFAULT NULL,
  `DNI` VARCHAR(11) NOT NULL,
  `MATRICULA` VARCHAR(5) NOT NULL,
  `IMPUESTO` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`NUMERO`),
  INDEX `FK_CLIENTE` (`DNI` ASC) VISIBLE,
  INDEX `FK_VENDEDOR` (`MATRICULA` ASC) VISIBLE,
  CONSTRAINT `FK_CLIENTE`
    FOREIGN KEY (`DNI`)
    REFERENCES `ventas_jugos`.`tb_cliente` (`DNI`),
  CONSTRAINT `FK_VENDEDOR`
    FOREIGN KEY (`MATRICULA`)
    REFERENCES `ventas_jugos`.`tb_vendedor` (`MATRICULA`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ventas_jugos`.`tb_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_jugos`.`tb_producto` (
  `CODIGO` VARCHAR(10) NOT NULL,
  `DESCRIPCION` VARCHAR(100) NULL DEFAULT NULL,
  `SABOR` VARCHAR(50) NULL DEFAULT NULL,
  `TAMANO` VARCHAR(50) NULL DEFAULT NULL,
  `ENVASE` VARCHAR(50) NULL DEFAULT NULL,
  `PRECIO_LISTA` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`CODIGO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ventas_jugos`.`tb_items_facturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_jugos`.`tb_items_facturas` (
  `NUMERO` VARCHAR(5) NOT NULL,
  `CODIGO` VARCHAR(10) NOT NULL,
  `CANTIDAD` INT NULL DEFAULT NULL,
  `PRECIO` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`NUMERO`, `CODIGO`),
  INDEX `FK_PRODUCTO` (`CODIGO` ASC) VISIBLE,
  CONSTRAINT `FK_FACTURA`
    FOREIGN KEY (`NUMERO`)
    REFERENCES `ventas_jugos`.`tb_factura` (`NUMERO`),
  CONSTRAINT `FK_PRODUCTO`
    FOREIGN KEY (`CODIGO`)
    REFERENCES `ventas_jugos`.`tb_producto` (`CODIGO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
