USE ventas_jugos;

SELECT * FROM tb_facturacion;

SELECT * FROM tb_factura1;
SELECT * FROM tb_items_factura1;

UPDATE tb_items_factura1 SET CANTRIDAD = 600
WHERE NUMERO = '0101' AND CODIGO  = '1002767';

DELETE FROM tb_items_factura1
WHERE NUMERO = '0104' AND CODIGO = '1004327';

DELIMITER //

CREATE TRIGGER TG_FATURACION_DELETE
AFTER DELETE ON tb_items_factura1
FOR EACH ROW BEGIN 
	DELETE FROM tb_facturacion;
	INSERT INTO tb_facturacion
	SELECT FECHA, SUM(B.CANTIDAD * B.PRECIO) AS VENTA_TOTAL
	FROM tb_factura1 A
	INNER JOIN 
	tb_items_facturas1 B
	ON A.NUMERO = B.NUMERO
	GROUP BY A.FECHA;
END //


DELIMITER //

CREATE TRIGGER TG_FATURACION_UPDATE
AFTER UPDATE ON tb_items_factura1
FOR EACH ROW BEGIN 
	DELETE FROM tb_facturacion;
	INSERT INTO tb_facturacion
	SELECT FECHA, SUM(B.CANTIDAD * B.PRECIO) AS VENTA_TOTAL
	FROM tb_factura1 A
	INNER JOIN 
	tb_items_facturas1 B
	ON A.NUMERO = B.NUMERO
	GROUP BY A.FECHA;
END //

UPDATE tb_items_factura1 SET CANTRIDAD = 800
WHERE NUMERO = '0101' AND CODIGO  = '1002767';

DELETE FROM tb_items_factura1
WHERE NUMERO = '0104' AND CODIGO = '1013793';





