SELECT * FROM tabla_de_clientes ORDER BY NOMBRE;

SELECT * FROM tabla_de_clientes ORDER BY NOMBRE DESC;

SELECT * FROM tabla_de_clientes ORDER BY NOMBRE DESC, NOMBRE ASC;

SELECT * FROM tabla_de_productos ORDER BY PRECIO_DE_LISTA;

SELECT * FROM tabla_de_productos ORDER BY PRECIO_DE_LISTA DESC;

SELECT * FROM tabla_de_productos ORDER BY NOMBRE_DEL_PRODUCTO;

SELECT * FROM tabla_de_productos ORDER BY NOMBRE_DEL_PRODUCTO DESC;

SELECT * FROM tabla_de_productos ORDER BY ENVASE DESC, NOMBRE_DEL_PRODUCTO ASC;


