/*USUARIO COMUN*/

/* PARA CREAR UN NUEVO USUARIO POR COMANDO | IDENTIFIED BY es contraseña*/
CREATE USER 'user02'@'localhost' IDENTIFIED BY 'user02';

/**/
/*TO ES EL USUARIO*/
GRANT SELECT, INSERT, UPDATE, DELETE , 
CREATE TEMPORARY TABLES, LOCK TABLES,
EXECUTE
ON *.*  TO 'user02'@'localhost';









