/* PARACREAU UN NUEVO USUARIO POR COMANDO*/
CREATE USER 'admin02'@'localhost' IDENTIFIED BY 'admin02';

/*PARA DAR PERMISO  (ASTERICO * = BASE DE DATOS=  
(ASTERISCO* = TODAS LAS TABLAS*/
/*TO ES EL USUARIO*/
GRANT ALL PRIVILEGES 
ON *.*  TO 'admin02'@'localhost' WITH GRANT OPTION;







