CREATE DATABASE jugos_ventas;
USE jugos_ventas;

SELECT CODIGO_DEL_PRODUCTO FROM tabla_de_productos;


SELECT A.CODIGO_DEL_PRODUCTO, C.CANTIDAD FROM tabla_de_productos A 
INNER JOIN items_facturas C 
ON A.CODIGO_DEL_PRODUCTO = C.CODIGO_DEL_PRODUCTO;

SELECT A.CODIGO_DEL_PRODUCTO, YEAR(FECHA_VENTA) AS AÑO, C.CANTIDAD FROM tabla_de_productos A 
INNER JOIN items_facturas C 
ON A.CODIGO_DEL_PRODUCTO = C.CODIGO_DEL_PRODUCTO
INNER JOIN facturas B
ON C.NUMERO = B.NUMERO;





